# Generated by Django 4.0 on 2022-01-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_learnership_duration'),
        ('applications', '0002_alter_application_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='yes_specify',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='agreement',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.learnership'),
        ),
        migrations.AlterField(
            model_name='application',
            name='disability',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='highest_qualification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='applications.highest_qualification'),
        ),
        migrations.AlterField(
            model_name='application',
            name='nk_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='south_african_citizen',
            field=models.CharField(choices=[('yes', 'Yes'), ('asylum', 'Asylum'), ('visa', 'Visa')], max_length=30, null=True),
        ),
    ]
