# Generated by Django 4.0 on 2022-01-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_birth_date_application_yes_specify_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='yes_specify',
            new_name='if_yes_specify',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='nk_cellphone',
            new_name='next_of_keen_cellphone',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='nk_email',
            new_name='next_of_keen_email',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='nk_home_tel',
            new_name='next_of_keen_home_tel',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='nk_name',
            new_name='next_of_keen_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='nk_surname',
            new_name='next_of_keen_surname',
        ),
    ]
