# Generated by Django 4.0 on 2022-01-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_yes_specify_application_if_yes_specify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
    ]
