# Generated by Django 4.0 on 2022-01-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='course',
            field=models.CharField(choices=[('Learnership', 'Learnership'), ('Short Courses', 'Short Courses'), ('Skills Program', 'Skills Program'), ('Work Readiness Program', 'Work Readiness Program'), ('Financial Literacy', 'Financial Literacy'), ('Data Science & Python', 'Data Science & Python'), ('Digital Immersion Program', 'Digital Immersion Program'), ('Specialized Development Program', 'Specialized Development Program'), ('Animation Program', 'Animation Program')], default='Learnership', max_length=50),
        ),
    ]
