# Generated by Django 4.0 on 2022-01-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='highest_qualification',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
