# Generated by Django 4.0 on 2022-01-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_highest_qualification_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='highest_qualification',
            new_name='qualification',
        ),
    ]
