# Generated by Django 4.0 on 2022-01-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_rename_highest_qualification_application_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highest_qualification',
            name='enabled',
        ),
        migrations.AddField(
            model_name='highest_qualification',
            name='qualification_number',
            field=models.IntegerField(auto_created=True, default=0),
        ),
    ]
