# Generated by Django 4.0 on 2022-01-06 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_remove_highest_qualification_enabled_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highest_qualification',
            new_name='Qualification',
        ),
    ]
