# Generated by Django 4.0 on 2022-01-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_rename_highest_qualification_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_number',
        ),
    ]
