# Generated by Django 4.0 on 2022-01-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('cell', models.CharField(max_length=255)),
                ('message', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
