# Generated by Django 4.0 on 2022-01-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='2022-XABC1F', max_length=32),
        ),
    ]
