# Generated by Django 4.0 on 2022-02-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_profile_birthday_remove_profile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='2022-2N1RWG', max_length=32),
        ),
    ]
