# Generated by Django 4.0 on 2022-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='2022-7NACUR', max_length=32),
        ),
    ]
