# Generated by Django 4.0 on 2022-01-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('responsible_party', models.CharField(blank=True, default='Sisekelo', max_length=100, null=True)),
                ('make', models.CharField(max_length=200)),
                ('serial_number', models.IntegerField()),
                ('color', models.CharField(max_length=50, null=True)),
                ('lended_at', models.DateTimeField(auto_now_add=True, verbose_name='Date lended')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('condition', models.CharField(choices=[('EX', 'Excellent'), ('SC', 'Scratched'), ('BR', 'Broken'), ('MI', 'Missing')], default='EX', max_length=20)),
                ('lendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lendee', to='auth.user')),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
