# Generated by Django 4.0 on 2022-03-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('inventory', '0003_alter_device_description_alter_device_lender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='lended_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lendee',
        ),
        migrations.RemoveField(
            model_name='device',
            name='lender',
        ),
        migrations.CreateModel(
            name='Lended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lended_at', models.DateTimeField(auto_now_add=True, verbose_name='Date lended')),
                ('serial_number', models.CharField(max_length=50)),
                ('lending_condition', models.CharField(choices=[('EX', 'Excellent'), ('SC', 'Scratched'), ('BR', 'Broken'), ('MI', 'Missing')], default='EX', max_length=20)),
                ('lended_laptop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop', to='inventory.device')),
                ('lendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lended_person', to='auth.user')),
                ('lender', models.ForeignKey(blank=True, default='Sisekelo', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
