# Generated by Django 4.0 on 2022-01-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accredited_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specialized_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Learnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='uploads/learnership_images/')),
                ('mode_of_delivery', models.CharField(choices=[('O', 'Online'), ('P', 'Physical'), ('H', 'Hybrid')], max_length=1)),
                ('credits', models.IntegerField()),
                ('outcomes', models.TextField(default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('duration', models.DurationField(default='')),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('modules', models.TextField(default='')),
                ('brochure', models.FileField(upload_to='uploads/learnership_brochures')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('nfq_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfqlevel', to='courses.nfq')),
            ],
        ),
    ]
