# Generated by Django 4.0 on 2022-01-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnership',
            name='outcomes',
        ),
        migrations.AddField(
            model_name='learnership',
            name='expectations',
            field=models.TextField(blank=True),
        ),
    ]
