# Generated by Django 4.0 on 2022-01-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_learnership_outcomes_learnership_expectations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnership',
            name='duration',
            field=models.DurationField(),
        ),
    ]
