# Generated by Django 4.0 on 2022-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_learnership_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_Catalogues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/learnership_images/')),
                ('mode_of_delivery', models.CharField(choices=[('O', 'Online'), ('P', 'Physical'), ('H', 'Hybrid')], default='O', max_length=1)),
                ('expectations', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('duration', models.DurationField(null=True)),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('overview', models.TextField(default='')),
                ('skills_brochure', models.FileField(null=True, upload_to='uploads/learnership_brochures')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='accredited_brochure',
            field=models.FileField(null=True, upload_to='uploads/learnership_brochures'),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='expectations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/learnership_images/'),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='mode_of_delivery',
            field=models.CharField(choices=[('O', 'Online'), ('P', 'Physical'), ('H', 'Hybrid')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='expectations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/learnership_images/'),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='mode_of_delivery',
            field=models.CharField(choices=[('O', 'Online'), ('P', 'Physical'), ('H', 'Hybrid')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='specialized_brochure',
            field=models.FileField(null=True, upload_to='uploads/learnership_brochures'),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='start_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
