# Generated by Django 4.0 on 2022-01-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_program_catalogues_skills_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnership',
            name='certificate_type',
            field=models.CharField(choices=[('National Certificate', 'National Certificate'), ('Further Education & Training', 'Further Education & Training')], default='National Certificate', max_length=50),
        ),
    ]
