# Generated by Django 4.0 on 2022-01-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_accredited_program_mode_of_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accredited_program',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
