# Generated by Django 4.0 on 2022-01-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_learnership_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills_program',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specialized_course',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
