# Generated by Django 4.0 on 2022-01-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_skills_program_duration_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program_Catalogues',
            new_name='Program_Catalogue',
        ),
    ]
