# Generated by Django 4.0 on 2022-01-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_learnership_id_learnership_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnership',
            name='slug',
            field=models.SlugField(default='', max_length=200, primary_key=True, serialize=False),
        ),
    ]
