# Generated by Django 4.0 on 2022-01-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_learnership_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnership',
            name='mode_of_delivery',
            field=models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical'), ('Hybrid', 'Hybrid')], max_length=10),
        ),
    ]
