# Generated by Django 4.0 on 2022-01-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_learnership_mode_of_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Short_Courses',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/learnership_images/')),
                ('mode_of_delivery', models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical'), ('Hybrid', 'Hybrid')], default='O', max_length=30)),
                ('expectations', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('overview', models.TextField(default='')),
                ('accredited_brochure', models.FileField(null=True, upload_to='uploads/learnership_brochures')),
                ('slug', models.SlugField(default='', max_length=200, primary_key=True, serialize=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
