# Generated by Django 4.0 on 2022-01-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_short_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Short_Courses',
            new_name='Short_Course',
        ),
    ]
