# Generated by Django 4.0 on 2022-01-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_rename_short_courses_short_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accredited_program',
            name='accredited_brochure',
        ),
        migrations.RemoveField(
            model_name='accredited_program',
            name='id',
        ),
        migrations.RemoveField(
            model_name='accredited_program',
            name='overview',
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='brochure',
            field=models.FileField(default='', upload_to='uploads/learnership_brochures'),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='certificate_type',
            field=models.CharField(choices=[('National Certificate', 'National Certificate'), ('Further Education & Training', 'Further Education & Training')], default='National Certificate', max_length=50),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='credits',
            field=models.IntegerField(default='130'),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='modules',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='nfq_level',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='nfqlevel1', to='courses.nfq'),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='program_type',
            field=models.CharField(choices=[('Learnership', 'Learnership'), ('Short Courses', 'Short Courses'), ('Skills Program', 'Skills Program')], default='Learnership', max_length=50),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='slug',
            field=models.SlugField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accredited_program',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='accredited_program',
            name='mode_of_delivery',
            field=models.CharField(choices=[('Online', 'Online'), ('Physical', 'Physical'), ('Hybrid', 'Hybrid')], max_length=10),
        ),
    ]
