# Generated by Django 4.0 on 2022-01-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_remove_accredited_program_accredited_brochure_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Online',
        ),
        migrations.DeleteModel(
            name='Skills_Program',
        ),
        migrations.AddField(
            model_name='specialized_course',
            name='program_type',
            field=models.CharField(choices=[('Work Readiness Program', 'Work Readiness Program'), ('Financial Literacy', 'Financial Literacy'), ('Data Science & Python', 'Data Science & Python'), ('Digital Immersion Program', 'Digital Immersion Program'), ('Specialized Development Program', 'Specialized Development Program'), ('Animation Program', 'Animation Program')], default='Work Readiness Program', max_length=50),
        ),
        migrations.AlterField(
            model_name='accredited_program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
