# Generated by Django 4.0 on 2022-01-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_delete_online_delete_skills_program_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accredited_program',
            old_name='slug',
            new_name='course_slug',
        ),
    ]
