# Generated by Django 4.0 on 2022-01-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_rename_slug_accredited_program_course_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accredited_program',
            old_name='course_slug',
            new_name='slug',
        ),
    ]
