# Generated by Django 4.0 on 2022-01-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_course_slug_accredited_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accredited_program',
            name='target_audiences',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Upskilling', 'Upskilling'), ('Expert', 'Expert')], default='Beginner', max_length=10),
        ),
    ]
