# Generated by Django 4.0 on 2022-01-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_accredited_program_target_audiences'),
    ]

    operations = [
        migrations.AddField(
            model_name='accredited_program',
            name='career_prospects',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='accredited_program',
            name='payment_options',
            field=models.CharField(choices=[('EFT', 'EFT'), ('CARD', 'CARD'), ('BANK TRANSFER', 'BANK TRANSFER')], default='Beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='accredited_program',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accredited_program',
            name='target_audiences',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Upskilling', 'Upskilling'), ('Expert', 'Expert')], default='Beginner', max_length=50),
        ),
    ]
